# Generated by Django 5.1.1 on 2024-10-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_to_know_us', models.CharField(max_length=50)),
                ('make_money_with_us', models.CharField(max_length=50)),
                ('amazon_payment_products', models.CharField(max_length=50)),
                ('let_us_help_you', models.CharField(max_length=50)),
            ],
        ),
    ]
