# Generated by Django 5.1.1 on 2024-10-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=50)),
                ('shop_categ_img', models.FileField(blank=True, default=None, max_length=500, null=True, upload_to='shopping_category/')),
            ],
        ),
    ]
