# Generated by Django 5.1.1 on 2024-10-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(blank=True, max_length=50)),
                ('Desc', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
