# Generated by Django 5.1.1 on 2024-10-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useerdetails',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='useerdetails',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
